### ISSUE TITLE
Use Case: Efficiency in reviewing contributions from first-time contributors

### ISSUE THREAD

**Issue by rpaik** [chaoss/wg-gmd#33]
A first-time contributor could be easily discouraged if no one reviews/acknowledges their work in a timely manner. Following are number of questions that can help evaluate responsiveness for first-time contributors. 

- What percentage of first-time contributions are accepted?
- What percentage of contributions from first-time contributors are accepted vs. `core developers`?
- How long does it take (e.g. average or median) for first-time contributions to be `resolved` (e.g. accepted or declined)?
- How long does it take (e.g. average or median) for contributions from `core developers` to be `resolved` (e.g. accepted or declined)?
- How long does it take (e.g. average or media) for first-time contributions to be responded to (e.g. acknowledgment, first review, etc.)? 
- How long does it take (e.g. average or median) for contributions from `core developers` to be responded to (e.g. acknowledgment, first review, etc.)? 
- Does the acceptance of first-time contribution have an effect on future contributions from the same contributor? 
- Does the responsiveness to first-time contribution (e.g. average/median time for acknowledgement, first review, etc.) have an effect on future contributions from the same contributor?

**Comment by GeorgLink** [comment]
Thanks @rpaik 

First-time contributors seem to be easily defined as those who have no prior contributions.

Do we have a definition for `core developers` (or `core contributors`)?

**Comment by jgbarah** [comment]
@GeorgLink said:

> Do we have a definition for core developers (or core contributors)?

Good question. Maybe we could work with an intuitive idea of what core developers (contributors) are, as those who perform most of the contributions, until we define the specific metrics.

In any case, we could define that either:

* In administrative terms: developers with admin privileges, or nominated as such by the project (which is difficult to generalize, but in some specific cases, such as GitHub, could be particularized as people with admin and/or merge rights on the repository)
* In quantitative terrms. Following the 80-20 rule, we could consider people producing 80% of the contributions over a certain period of time (eg, since the start of the project, or during the last six months).

But maybe we can think about the questions, and then metrics, based on that we can define "core", to sidstep that issue...

In fact, I wonder if that could lead to another use case: "Knowledge about who are core contributors to a project". What do you think?

**Comment by jgbarah** [comment]
When particularizing, we should also define "contribution". For example, a commit is (I think) clearly a contribution. Maybe, at least for a start, we could concentrate on this. But there are other kinds of conributions... What do you think @rpaik: for focusing, we consider only code contributions in the form of commits, or we try to extend to other kinds of contributions?

(I would focus on code contributions, for focusing the case, at least until we have things more clear, and then maybe extending it to other contributions, or opening another use case for that).

**Comment by jgbarah** [comment]
For the questions, from my side we could start with these ones, and start thinking about metrics for answering them right away.

**Comment by sgoggins** [comment]
I wonder if "core" contributors need something of an explicit definition. For example, perhaps this means maintainers? Or, it could be people who are active in several aspects of the project above a certain threshold? Or, is it newcomers or "not newcomers"

**Comment by jgbarah** [comment]
Let's use some vocabulary definitions, for terms like "contributor", "new contributor", and "core developer", so that the use case is more clear.

**Comment by jgbarah** [comment]
I've opened #40 for having this section with a vocabulary in use cases.

**Comment by rpaik** [comment]
> When particularizing, we should also define "contribution". For example, a commit is (I think) clearly a contribution. Maybe, at least for a start, we could concentrate on this. But there are other kinds of conributions... What do you think @rpaik: for focusing, we consider only code contributions in the form of commits, or we try to extend to other kinds of contributions?
> 
> (I would focus on code contributions, for focusing the case, at least until we have things more clear, and then maybe extending it to other contributions, or opening another use case for that).

I agree @jgbarah.  I think we can focus on code contribution for now.  As for the definition of "core contributors", I think we should use what we already have at https://github.com/chaoss/grimoirelab-sigils/blob/master/doc/community-structure.md.  So it could be something like people who made 80% of contribution over the 6 month period (or may be a year).  I'll also add my comments on https://github.com/chaoss/wg-gmd/pull/40

**Comment by jgbarah** [comment]
OK, if nobody objects, let's focus, at least for now, on git contributions (commits). That would make "contributors" as "people who are authors of commits", right? (notice that I'm saying "people" and not "identities", since I guess it is persons what matters here).

We can also consider that core is the minimum set of contributors with a certain percentage of participation (such as 80%) during some period of time (eg, last 6 months). Those could later be parameters for the metrics, if convenient.

**Comment by sgoggins** [comment]
I think we risk creating a box that we are stuck in if we become quantitatively precise in our definition of "core contributors" in this way. These percentages smell more like parameters or filters that we would apply to specific metrics like "commits". 

What would a definition look like then? 

First, I think we are defining "core code contributors", not "core contributors"; as "core contributors" does not automatically include only code. And if we define it this way now we are, again, "boxed in" I think when we move on to "issues" and "comments" and "documentation" and other kinds of contribution that are essential for a project. 

There are also phenomena that make something like "total commits" gameable, even in some cases accidentally. Lines of code as another metric might be a way of balancing this gameability.

Suggestion: Differentiate between people with commit rights and others. Describe a "code contribution" distribution based on number of commits and a separate metric based on LOC.  "Distribution" seems like a term that we may want to define as the specification of different statistical models of distribution (power law, etc.). Percentages mean substantially different things in communities that are governed differently (highly centralized v highly distributed). 

That's an idea.  

Here's a couple papers that my thoughts emerge from: 
Greater diversity in how we measure performance and participation: https://goo.gl/Mp6GjB
The role of project/repo leadership models in how commit metrics emerge: https://goo.gl/6ZUJqv

Looking at these 80% measures preference specific models for project leadership; in a sense, it risks "encasing" or "putting in a box" the way that we define important code contributions.

**Comment by jgbarah** [comment]
I agree that having a specific definition of core contributions is going to cause some boxing, to a use case that could be useful in any case. So, one idea could be to avoid defining "core", and let that to the user of the use case.

OTOH, any kind of more precise definition is going to cause some "boxing". For example, if we define based on commit rights, that's going to be dependent on project policies: some are very liberal with granting commit rights, while some others are very strict. That could render any metric we derive as not suitable for comparison.

Just to unblock this, I propose one of these two ways out:

* We stick to defining core commit contributors based on a people producing a significant fraction of all commits (eg, 80%, but that could be variable).
* Letting "core commit contributors" be undefined, and for each use of this use case, you should define core commit contributors.

I would go for the first, since (at least in my view) use cases are specific to some goal and some stakeholders. If we find that a certain definition of core is good enough for the goals and stakeholders for this use case, maybe that´s good enough. Then, when we do the complete goal-question-metric analysis for a case derived from (or related to) this use case, we can consider the more general use case where we have more general ways of defining core, or leave it as a parameter of the goal...

WDYT??

**Comment by jgbarah** [comment]
> Looking at these 80% measures preference specific models for project leadership; in a sense, it risks "encasing" or "putting in a box" the way that we define important code contributions.

A final note. As I commented above, use cases are always going to consider a certain option among all the possible ones. Of course there are many other ways of contributing, but if for an specific stakeholder commits is the one they want to consider, that's fine. We can of course have other alternative, or more general, use cases. Same for how they define "core", if that is important for their scenario.

In the end, my guess is that we are not "mandating" how use cases should be. They are use cases, and that's it, that's all: how people intend to use metrics, or how they are using them already. Of course, when doing our goal-question-metric analysis, we need to be much more exhaustive, precise, and "fair". And if we have a goal of "measuring contributions of newcomers", we need to be very careful of defining "contributions", "newcomers", and how and with what we compare them. Hopefully, we will be able of doing that based on several use cases, or their discussion. For example now, even not having the use case complete, we already have learned a lot about what to have into account when working with contributions by newcomers.

**Comment by rpaik** [comment]
To make things simple, we can look only at questions for `first-time contributors` to start with.  I think comparison against more experienced contributors are definitely interesting, but if defining what we mean by `experienced contributors` isn't straightforward I think we can skip that for now.

BTW, I'm not sure if LOC is any better than the number of commits.  Just because someone wrote more LOC doesn't mean that person's contribution is more valuable vs. others.....

**Comment by jgbarah** [comment]
OK, if you agree, let's do it this way:

* For the description of the use case, and goals, let's just mention "code contributions", "new contributors" and "experienced contributors" (I use "new" instead of "first-time" to allow for some metrics comparing eg, the first three commits instead of just the first one).

* For the questions / metrics, let's make this particular, following the xx% rule over a certain period for defining "experienced", using commits (instead of LOC) for now, and focusing on commits and pull / merge requests.

* In the definitions section, let's define  "code contributions", "new contributors" and "experienced contributors"  as above, but indicating that other definitions (and therefore, related use cases) are possible.

Then, let's work on the questions, and then metrics, and let's try the results, to see how they work.

At any moment we want, we ca write a derived used case with other definitions for "code contributions", "new contributors" and "experienced contributors", with other derived questions and metrics, and compare results, if we want.

In any case, when we feed this back into our goal-question-metric methodology for the correspondent focus area, we have into account all the possibilities we're discussing here.

Is this good enough, @rpaik @sgoggins (and others) to move forward for now? If so, I can write the first draft of the use case based on this, and pull request it.

**Comment by sgoggins** [comment]
@rpaik @jgbarah : I agree that we will make the use cases specific, which ensures that we get solid stakeholder engagement. 

The Goals/Questions/Metrics may be parameterized in a way to support use cases.

**Comment by jgbarah** [comment]
Great! In this case, except if @rpaik says otherwise, I will produce a pull request with the first draft for this use case, based on the original proposal and the discussion here.

**Comment by jgbarah** [comment]
I've produced a pull request, #63, to start introducing metrics in the use case. Feedback is welcome.

**Comment by sgoggins** [comment]
@rpaik : Can we close this issue? Two pull requests are merged. Do they capture what you expected?

**Comment by rpaik** [comment]
Sorry for the delay.  Yes I'm good with this 😄
