### ISSUE TITLE
GMD: Open issue age - to average or not to average?

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/wg-gmd#6]
Following #1,
[Open issue age](https://github.com/chaoss/metrics/blob/master/activity-metrics/open-issue-age.md), do we calculate the average age of all the open issues or do we look at each issue individually? I think that latter is better because that way we know which issues have been neglected for too long and can also create good visualisations.

**Comment by GeorgLink** [comment]
I think both are valid ways for displaying and filtering the open issue age. The implementation is a choice of the implementer.

**Comment by jgbarah** [comment]
But I think still we need an aggregator, if the metric is to be understood as a such (eg, a measurement).

If we agree to use an aggregator, I would use the median, because distributions of this kind tend to be very skewed, and the mean does not provide much information (not being the distribution normal). Maybe a better approach is to (when defining the metric) state that "appropriate statistics of the distribution of open issue age" will be provided, and in the examples provide information for example for median, 75, 90, 95 percentiles, mean and variance (or something like that). Comments, anyone?

**Comment by GeorgLink** [comment]
​+1 to percentiles, although a visual representation may be easier to
comprehend for most uses.

**Comment by jgbarah** [comment]
I agree with having also a visual representation. I think that for all metrics, we could have some aggregators, and one or more "preferred" visualizations.

**Comment by aswanipranjal** [comment]
@jgbarah, @GeorgLink: I'll calculate the percentile, mean and variance. And i'll create a visualization so we can use what we like.

**Comment by jgbarah** [comment]
Closing this as it seems it doesn't need further discussion.
